// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/5/13 11:37:56
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/lizhenhu/Desktop/zhihe-0508-2/language-vocab-book/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-2/language-vocab-book/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-2/language-vocab-book/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-2/language-vocab-book/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-2/language-vocab-book/plugins/**/*.{js,ts,mjs}","/Users/lizhenhu/Desktop/zhihe-0508-2/language-vocab-book/composables/**/*.{js,ts,mjs}","/Users/lizhenhu/Desktop/zhihe-0508-2/language-vocab-book/utils/**/*.{js,ts,mjs}","/Users/lizhenhu/Desktop/zhihe-0508-2/language-vocab-book/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-2/language-vocab-book/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-2/language-vocab-book/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/lizhenhu/Desktop/zhihe-0508-2/language-vocab-book/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;